language: python
python:
  - "3.4"
dist:
  - "trusty"
# command to install dependencies
addons:
  apt:
    packages:
    - python3-setuptools
install: 
- "pip install -U pip"
- "pip install -U jupyter_client ipykernel jupyter setuptools"
- "pip install -r requirements.txt"
- "git clone --recursive https://github.com/dmlc/xgboost"
- "cd xgboost; make -j4"
- "cd python-package; python setup.py install"
- "cd ../../; ls -al"
# command to run tests
script: travis_wait jupyter-nbconvert --execute hw3.ipynb --ExecutePreprocessor.timeout=None
